### PR TITLE
created-contact.form

### PR DESCRIPTION
**Pull request by EvansSnave**
Created the contact form with placeholders trying to keep the resemblance with the template as much as possible.  Solved linter issues. Added contact form inputs: name, email and message. Solved issues with the brach and solved backroud issue where we were not able to use two background for the contact form

### CODE REVIEW

**Review by stanleySimeon — CHANGES_REQUESTED** [review]
Hi @EvansSnave, @ahmedeid6842 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# ⚠️ Invalid Code Review Request ⚠️ 

You have submitted a project, that does not have a descriptive Pull Request (PR). The PR descriptions should contain a summary of the changes you have in the project/PR. This gives the reviewer an idea of the changes that took place in this particular PR. Kindly fix this before requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Kamba56 — COMMENTED** [review]
Hi @EvansSnave

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **has a merged PR** Kindly click on the `revert` button to revert changes of your PR and submit an open PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by EvansSnave** [comment]
Hi @Kamba56. I don't have that option fro some reason and I already tried reverting the merge in git but wasn't able. Should I create a new pull request?

**Comment by Kamba56** [comment]
> Hi @Kamba56. I don't have that option fro some reason and I already tried reverting the merge in git but wasn't able. Should I create a new pull request?

If you create new pull request, you might loose your changes, the pull request will he without visible changes

**Comment by Kamba56** [comment]
You can't see a button to revert in your PR?🤔

**Comment by EvansSnave** [comment]
Hello. Yes, that is right. I only have the button to view detail but not
revert

**Pull request merged**
