### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by EvansSnave**
In Style.css me and my coding partner added an animation for the "get in touch" button (the last one) to increase its size and change background and text color when hovered on. My coding partner will not apper in this PR. He appears in my other pull request: https://github.com/EvansSnave/Mobile-design/pull/6. BUt i accidentally merged that with the main branch and i dont have the option to revert the merge. Is it possible to review this PR or the other? In this one I have been told it's unvalid because my partert did not participated and in the other they told me it could not be reviewed because of the merge.

### CODE REVIEW

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @EvansSnave , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that you did not work on with your partner, and remember that this milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @EvansSnave , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that you did not work on with your partner, and remember that this milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @EvansSnave , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that you did not work on with your partner, and remember that this milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by EvansSnave** [comment]
@Owusu-Desmond Hi .My pull request with my parter was the one I accidentally merged with my main branch. I dont have the option to reset the merge that is why I created this new pull request. Can you review my other PR? the one I merged. My coding partner is resting until monday so I cannot ask him to add changes.

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @EvansSnave, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Form tag ✔️
- input and textarea tags usage ✔️
- Linters passed ✔️

## Required Changes ♻️
_Check the comments under the review._
## I went on reviewing this because of the message you left here and also the additional message you left when you submitted the PR, upon reaching you, you provided me [this](https://raw.githack.com/EvansSnave/Mobile-design/b36b7d9a0689e7b261fa92149bb7d28ab92076c0/Index.html) link to be the one you mistakingly merged. I could see two participants there and also form section implementation, kindly always be careful to always get approval before you merge your PR.
- [ ] I could see that you are yet to use use the personal id from formspree, you will need to open an account with formspree.io and add the id they give you to the place where form_id is as I pointed in the image below:
image

## What I get when I submitted the form
image

- [x] I would implore you to add the required attribute to the textarea tag too so that an empty form won't be submitted.
- [x] I would implore you to also add the maxlength="30" to the name input so that the character to be input can be controlled by you. Same for the textarea too, it should take maxlength="500".
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by EvansSnave** [comment]
Thank you so much. I fixed the errors!

**Review by binhussen — APPROVED** [review]
Hi @EvansSnave , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- Integrated with [formspree service](https://formspree.io/html) ✔️
- Form Validated ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by EvansSnave** [comment]
Thank you so much and sorry for the inconveniences

**Pull request merged**
