### PR TITLE
desktop-version

### PR DESCRIPTION
**Pull request by EvansSnave**
Created desktop version. In stule.css added media querys for the responsive design. The navbar is fixed when in desktop size. Text and images change when switching from mobile version
In index.html changed some containers order and added classes to elements from previous sections.

### CODE REVIEW

**Comment by EvansSnave** [comment]
I think my linter is having issues. I already fixed all the error but it is still showing I didn't. I searched in internet and it seems to be a linter bug. That's why I haven't been able to solve my linter error in this PR

**Comment by Strangeal** [comment]
@EvansSnave I just checked your `linters` on local and everything is passing so I will go ahead and review your project now.

**Comment by EvansSnave** [comment]
Hi. Did you reviewed my code?

**Review by didierganthier — COMMENTED** [review]
Hi @EvansSnave ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.



## Invalid Code Review Request 🚫

- You have submitted a project with the Stylelint linters test failing, see below the [lines](https://github.com/EvansSnave/Mobile-design/actions/runs/4904129849/jobs/8756961108?pr=7) that are failing 👇🏽 

Screenshot 2023-05-06 at 23 41 31

- Also make sure to use correct GitHub flow, the PR should be from `desktop-version` to `main`, not from `main` to `desktop-version` (might also be why the linters are failing)
Screenshot 2023-05-06 at 23 42 28
- Also make sure that you're the only contributor as this is a solo milestone, I can see commit from @ahmedeid6842 ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

**Pull request merged**
